# Filename: ~/github/containerdata-public/docker/unifi-network-application/docker-compose.yml

# docker compose -f ~/github/containerdata-public/docker/unifi-network-application/docker-compose.yml up -d

version: "3.8"
services:
  unifi-network-application:
    container_name: unifi-network-application
    restart: unless-stopped

    # https://github.com/linuxserver/docker-unifi-network-application/releases
    image: lscr.io/linuxserver/unifi-network-application:8.0.28-ls29

    ports:
      # See description of ports in
      # https://github.com/linuxserver/docker-unifi-network-application?tab=readme-ov-file#parameters
      - 3478:3478/udp # unifi STUN port
      - 10001:10001/udp # for AP discovery
      - 8080:8080 # for device communication
      - 8443:8443 # web admin port
    # Below ones are optional
    # - 1901:1900/udp # (optional) make controller discoverable on L2 network
    # - 8843:8843 # (optional) guest portal HTTPS redirect port
    # - 8880:8880 # (optional) guest portal HTTP redirect port
    # - 6789:6789 # (optional) mobile throughput test
    # - 5514:5514/udp # (optional) remote syslog port

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Guatemala
      - MONGO_USER=unifi
      - MONGO_PASS=
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 # optional
      - MEM_STARTUP=1024 # optional
      - MONGO_TLS= # optional
      - MONGO_AUTHSOURCE= # optional
    volumes:
      - ./config:/config

    secrets:
      - SECRET_USER
      - SECRET_PASS

secrets:
  SECRET_USER:
    file: ./.secrets/SECRET_USER.txt
  SECRET_PASS:
    file: ./.secrets/SECRET_PASS.txt
