# Filename: ~/github/containerdata-public/docker/mongo/docker-compose.yml

# docker compose -f ~/github/containerdata-public/docker/mongo/docker-compose.yml up -d

version: "3.8"
services:
  mongo:
    container_name: mongo
    restart: unless-stopped

    # https://hub.docker.com/_/mongo/tags
    image: mongo:7.0.5

    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/SECRET_USER
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/SECRET_PASS

    volumes:
      - ./data:/data/db

    secrets:
      - SECRET_USER
      - SECRET_PASS

  # web-based administration interface for MongoDB databases
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

# This is what maps the secrets to the actual file,
# They're in the hidden '.secrets' folder in the same directory as my docker-compose file
secrets:
  SECRET_USER:
    file: ./.secrets/SECRET_USER.txt
  SECRET_PASS:
    file: ./.secrets/SECRET_PASS.txt
